Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/texttest.py", line 470, in __init__
    exec importCommand
  File "<string>", line 1, in ?
  File "/nfs/vm/apc_temp/test_texttesttmp/texttestgeoff11Aug18:08:31/TestSelf/ErrorHandling/BadConfig/wibble.py", line 23, in ?
    sdvdsd
NameError: name 'sdvdsd' is not defined
Could not use application dip - config_module wibble contained errors and could not be imported
