TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff22Sep112717/QueueSystems/ErrorHandling/Console/SlaveCrash based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application HELLO
WARNING : caught exception while running HELLO test-case Test changing state to UNRUNNABLE :
  HELLO test-case Test not compared:
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/engine.py", line 31, in handleExceptions
    return method(*args)
  File "/users/geoff/work/master/Testing/TextTest/testmodel.py", line 411, in callAction
    return action(self)
  File "/users/geoff/texttesttmp/texttest.sgegeoff22Sep112717/QueueSystems/ErrorHandling/Console/SlaveCrash/customconfig.py", line 18, in __call__
    wibble
NameError: global name 'wibble' is not defined

