TextTest will write diagnostics in /users/mattias/texttesttmp/texttest.sge.28Oct151904/QueueSystems/ErrorHandling/Console/SlaveCrash based on file at /users/mattias/work/master/Testing/Automatic/texttest/log4py.conf
Using Application HELLO
WARNING: Caught exception while running HELLO test-case Test changing state to UNRUNNABLE :
  HELLO test-case Test not compared:
Traceback (most recent call last):
  File "/users/mattias/work/clean_master/Testing/TextTest/engine.py", line 31, in handleExceptions
    return method(*args)
  File "/users/mattias/work/clean_master/Testing/TextTest/testmodel.py", line 388, in callAction
    return action(self)
  File "/users/mattias/texttesttmp/texttest.sge.28Oct151904/QueueSystems/ErrorHandling/Console/SlaveCrash/customconfig.py", line 18, in __call__
    wibble
NameError: global name 'wibble' is not defined

