<-PYT:subprocess.call(['cvs', '-q', 'help'], stderr=<open file '/dev/null', mode 'w' at 0x16156f0>, stdout=<open file '/dev/null', mode 'w' at 0x1615810>)
->RET:raise exceptions.OSError('[Errno 2] No such file or directory')
