Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/testmodel.py", line 598, in __init__
    exec importCommand
  File "<string>", line 1, in ?
  File "/users/geoff/work/master/Testing/Automatic/texttest/error_config_modules/errimporting.py", line 1, in ?
    import svsdsvgdf
ImportError: No module named svsdsvgdf
Could not use application dip - config_module errimporting contained errors and could not be imported
