Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/lib/default/actionrunner.py", line 229, in handleExceptions
    method(*args)
  File "/users/geoff/work/master/Testing/TextTest/lib/testmodel.py", line 573, in callAction
    return action(self)
  File "/carm/proj/texttest-tmp/geoff/texttest.13Aug160400.3588/texttest/GUI/DynamicGUI/Filtering/HideUnrunnable/customconfig.py", line 14, in __call__
    raise Exception, "Don't do simple tests!"
Exception: Don't do simple tests!
Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/lib/default/actionrunner.py", line 229, in handleExceptions
    method(*args)
  File "/users/geoff/work/master/Testing/TextTest/lib/testmodel.py", line 573, in callAction
    return action(self)
  File "/carm/proj/texttest-tmp/geoff/texttest.13Aug160400.3588/texttest/GUI/DynamicGUI/Filtering/HideUnrunnable/customconfig.py", line 14, in __call__
    raise Exception, "Don't do simple tests!"
Exception: Don't do simple tests!
