Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/lib/default/actionrunner.py", line 228, in handleExceptions
    method(*args)
  File "/carm/proj/texttest-tmp/geoff/texttest.27Aug135921.15403/texttest/GUI/DynamicGUI/Filtering/HideUnrunnable/customconfig.py", line 14, in __call__
    raise Exception, "Don't do simple tests!"
Exception: Don't do simple tests!
Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/lib/default/actionrunner.py", line 228, in handleExceptions
    method(*args)
  File "/carm/proj/texttest-tmp/geoff/texttest.27Aug135921.15403/texttest/GUI/DynamicGUI/Filtering/HideUnrunnable/customconfig.py", line 14, in __call__
    raise Exception, "Don't do simple tests!"
Exception: Don't do simple tests!
