Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/lib/actionrunner.py", line 238, in handleExceptions
    return method(*args)
  File "/users/geoff/work/master/Testing/TextTest/lib/testmodel.py", line 586, in callAction
    return action(self)
  File "/carm/proj/texttest-tmp/geoff/texttest.04Mar165436/texttest/GUI/DynamicGUI/Filtering/HideUnrunnable/customconfig.py", line 14, in __call__
    raise Exception, "Don't do simple tests!"
Exception: Don't do simple tests!
Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/lib/actionrunner.py", line 238, in handleExceptions
    return method(*args)
  File "/users/geoff/work/master/Testing/TextTest/lib/testmodel.py", line 586, in callAction
    return action(self)
  File "/carm/proj/texttest-tmp/geoff/texttest.04Mar165436/texttest/GUI/DynamicGUI/Filtering/HideUnrunnable/customconfig.py", line 14, in __call__
    raise Exception, "Don't do simple tests!"
Exception: Don't do simple tests!
